# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: autoboost
      MONGO_INITDB_ROOT_PASSWORD: autoboost
      MONGO_INITDB_DATABASE: mastodon_autoboost
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: autoboost
      ME_CONFIG_MONGODB_ADMINPASSWORD: autoboost
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_URL: "mongodb://autoboost:autoboost@mongo:27017/mastodon_autoboost?authSource=admin"

volumes:
  db-data: